package prati_sgcq.view;

import prati_sgcq.view.colunas.FrmColuna;
import prati_sgcq.view.padroes.FrmPadroes;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import prati_sgcq.view.config.FrmMenuConfig;

/**
 *
 * @author rafael.lopes
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmAtividades
     */
    public FrmMenu() {
        initComponents();
        setTitle("Menu Principal");
        setResizable(false);
        setLocationRelativeTo(null);
        URL url = this.getClass().getResource("/Imagem/icon_sgcq_48.png");
        Image icone = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(icone);
        setTitle("Controle de Qualidade - Menu");
        setDefaultCloseOperation(HIDE_ON_CLOSE);

//        // Instancia um novo SystemTray
//        SystemTray tray = SystemTray.getSystemTray();
//
//        /**
//         * Pega uma imagem para definir como ícone.
//         *
//         * main.getClass().getClassLoader().getResource("icone.jpg") pega a
//         * imagem do pacote onde a Classe se encontra. Será bem útil na hora de
//         * exportar a aplicação.
//         */
//        Image imageIcon = new ImageIcon((this.getClass()
//                .getResource("/Imagem/icon_sgcq_48.png")))
//                .getImage();
//
//        // Instancia e Define o icone do TrayIcon
//        TrayIcon trayIcon = new TrayIcon(imageIcon);
//
//        // Define o auto-ajuste da imagem
//        trayIcon.setImageAutoSize(true);
//
//        /**
//         * Instancia um mouse listener para ser usado no TrayIcon
//         */
//        MouseListener mlOpcoes = new MouseListener() {
//
//            public void mouseClicked(MouseEvent e) {
//                
//            }
//
//            public void mousePressed(MouseEvent e) {
//            }
//
//            public void mouseReleased(MouseEvent e) {
//                /**
//                 * Se o mouse for clicado com a roda do mouse ou com o botão
//                 * direito fechará a aplicação.
//                 */
//                if (e.getButton() == 2 || e.getButton() == 3) {
//                    System.exit(0);
//                }
//                if (e.getClickCount() == 2) {
//                    setExtendedState(NORMAL);
//                }
//            }
//
//            public void mouseEntered(MouseEvent e) {
//            }
//
//            public void mouseExited(MouseEvent e) {
//            }
//        };
//        // adiciona o mouseListener no TrayIcon
//        trayIcon.addMouseListener(mlOpcoes);
//
//        try {
//            // Adiciona o Ícone no SystemTray
//            tray.add(trayIcon);
//        } catch (AWTException e) {
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnMinimizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPadroes = new javax.swing.JButton();
        btnColunas = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_minimizar.png"))); // NOI18N
        btnMinimizar.setFocusable(false);
        btnMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setIconTextGap(50);
        btnMinimizar.setMaximumSize(new java.awt.Dimension(60, 60));
        btnMinimizar.setMinimumSize(new java.awt.Dimension(60, 60));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnMinimizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMinimizar);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_fechar.png"))); // NOI18N
        btnFechar.setFocusable(false);
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setMaximumSize(new java.awt.Dimension(60, 60));
        btnFechar.setMinimumSize(new java.awt.Dimension(60, 60));
        btnFechar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFechar);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 120, 40));

        jToolBar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jToolBar3.setFloatable(false);
        jToolBar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_sgcq_48.png"))); // NOI18N
        jToolBar3.add(jLabel2);
        jToolBar3.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controle de Qualidade");
        jToolBar3.add(jLabel1);

        getContentPane().add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        jPanel2.setBackground(new java.awt.Color(171, 171, 201));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPadroes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPadroes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_padrao.png"))); // NOI18N
        btnPadroes.setText("Padrões");
        btnPadroes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnPadroes.setIconTextGap(20);
        btnPadroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadroesActionPerformed(evt);
            }
        });
        jPanel2.add(btnPadroes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        btnColunas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnColunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_coluna.png"))); // NOI18N
        btnColunas.setText("Colunas");
        btnColunas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnColunas.setIconTextGap(20);
        btnColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColunasActionPerformed(evt);
            }
        });
        jPanel2.add(btnColunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnConfig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_config_tools.png"))); // NOI18N
        btnConfig.setText("Config.");
        btnConfig.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnConfig.setIconTextGap(20);
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        txtTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fundo_menu.png"))); // NOI18N
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPadroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadroesActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Thread t1 = new Thread() {
            @Override
            public void run() {
                FrmPadroes frm = new FrmPadroes();
                frm.setVisible(true);
            }
        };
        t1.start();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPadroesActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        int option = JOptionPane.showConfirmDialog(
                null,
                "Tem certeza de que deseja fechar o aplicativo?",
                "Confirmação de Fechamento",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
//            LoginDAO loginDAO = new LoginDAO();
//            loginDAO.updateUserLogout(System.getProperty("user_id"));
//            loginDAO.createLogLoginLogout("Logout", System.getProperty("user"));
            System.exit(0);
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColunasActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Thread t1 = new Thread() {
            @Override
            public void run() {
                FrmColuna frm = new FrmColuna();
                frm.setVisible(true);
            }
        };
        t1.start();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnColunasActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmMenuConfig frm = new FrmMenuConfig(null, true);
        frm.setVisible(true);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        //this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColunas;
    private javax.swing.JButton btnConfig;
    public static javax.swing.JButton btnFechar;
    public static javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnPadroes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
